### ISSUE TITLE
cinnamon: Certain icons repeat with appindicator

### ISSUE THREAD

**Issue by SamBurgos** [linuxmint/mint19.2-beta#1]
**Describe the bug**
Some icons are repeated several times (this might happen with appindicator and so far the issue appears on a Skype and Remmina with appindicator enabled

**To Reproduce**
1. Install both Skype for Linux and a Remmina installation with AppIndicator enabled
2. On Cinnamon Settings turn on the option "enable indicator support"
3. Restart the machine or turn it on (options are also available instantly)
4. Open Skype or Remmina

**Expected behavior**
Only one tray icon/indicator is available

**Actual behaviour**
There are a lot of tray icon/indicator

**Frequency**
Does the issue happen:
- [x] Always
- [ ] Randomly

**Edition (Desktop environment):**
In which edition is this happening?
- [x] Cinnamon Edition
- [ ] MATE Edition
- [ ] Xfce Edition

**Live or post-install:**
Indicate if this is happening after the installation, or during the live session:
- [x] Post-install
- [ ] Live session

**Screenshots**

**Locale:**
I have tried the output on a machine with Spanish El Salvador, but issue also happens on an english machine

LANG=es_SV.UTF-8
LC_CTYPE="es_SV.UTF-8"
LC_NUMERIC="es_SV.UTF-8"
LC_TIME="es_SV.UTF-8"
LC_COLLATE="es_SV.UTF-8"
LC_MONETARY="es_SV.UTF-8"
LC_MESSAGES="es_SV.UTF-8"
LC_PAPER="es_SV.UTF-8"
LC_NAME="es_SV.UTF-8"
LC_ADDRESS="es_SV.UTF-8"
LC_TELEPHONE="es_SV.UTF-8"
LC_MEASUREMENT="es_SV.UTF-8"
LC_IDENTIFICATION="es_SV.UTF-8"
LC_ALL=

**Drivers:**
Graphics:
  Device-1: Intel HD Graphics 5500 vendor: Toshiba America Info Systems 
  driver: i915 v: kernel bus ID: 00:02.0 chip ID: 8086:1616 
  Display: x11 server: X.Org 1.20.5 driver: intel unloaded: modesetting 
  alternate: fbdev,vesa resolution: 1366x768~60Hz, 1366x768_60.00~60Hz 
  OpenGL: renderer: Mesa DRI Intel HD Graphics 5500 (Broadwell GT2) 
  v: 4.5 Mesa 19.1.1 compat-v: 3.0 direct render: Yes 

**Additional context**
You can check additional information in the bug report via Cinnamon, [the link to the bug report is here](https://github.com/linuxmint/cinnamon/issues/8704), since I wasn't sure if the issue is with the applications, Cinnamon or something else. Some additional screenshots are provided there

**Comment by corbin-auriti** [comment]
Confirmed with Skype and Remmina, although no issues with appindicator off.

**Comment by daddy33** [comment]
I have also the exact same issue with clipboard managers clipit and diodon, as well as with pcloud-drive.
I simply turned appindicator off for now.

**Comment by basilky** [comment]
Already reported at https://github.com/linuxmint/cinnamon/issues/8595

**Comment by daddy33** [comment]
> Already reported at [linuxmint/cinnamon#8595](https://github.com/linuxmint/cinnamon/issues/8595)

Different issue.

**Comment by clefebvre** [comment]
Fixed.
