### ISSUE TITLE
Update Manager Crashes

### ISSUE THREAD

**Issue by HopelessHarry** [linuxmint/mint19.2-beta#11]
**Describe the bug**
Update Manager Crashes & Closes.

**To Reproduce**
1. Go to update manager in the panel
2. Click on View then Linux Kernels
3. Cursor spins for a couple of seconds, then Update Manager Crashes & Closes.

**Expected behavior**
Installable Kernels should be shown

**Frequency**
Happens about 75% of the time.

**Edition (Desktop environment):**
In which edition is this happening?
- [*] Cinnamon Edition

**Live or post-install:**
Indicate if this is happening after the installation, or during the live session:
- [*] Post-install

**Screenshots**

**Locale:**
Paste the output of `locale`.
en_GB

**Drivers:**
Paste the output of `inxi -Gxx`.
Graphics:
  Device-1: Intel Core Processor Integrated Graphics vendor: Hewlett-Packard 
  driver: i915 v: kernel bus ID: 00:02.0 chip ID: 8086:0042 
  Display: x11 server: X.Org 1.19.6 driver: modesetting unloaded: fbdev,vesa 
  resolution: 1920x1080~60Hz 
  OpenGL: renderer: Mesa DRI Intel Ironlake Desktop v: 2.1 Mesa 19.0.2 
  direct render: Yes 

**Crash report:**

''Stack trace''
If you are reporting a crash. Go to "Software Sources" and enable the debug symbols. Then go to "System Reports" and extract the stack trace for your crash and paste it here.
No Crash report is Generated.

''Dmesg''
If you type `dmesg` in a terminal, you should see a line corresponding to the crash. Paste it here.
[ 6861.207171] mintUpdate[18421]: segfault at 0 ip 0000000000000000 sp 00007f2df2ff9ab8 error 14

**Additional context**

**Comment by clefebvre** [comment]
[146446.645640] mintUpdate[1002]: segfault at 8 ip 00007fd28e5c7ef3 sp 00007fd278e845d8 error 4 in libgtk-3.so.0.2200.30[7fd28e42c000+6f1000]

**Comment by clefebvre** [comment]
Fixed in mintupdate 5.5.0.

Can you still reproduce the error?

**Comment by HopelessHarry** [comment]
Resolved with new mintupdate.
