### ISSUE TITLE
Cinnamon installer keyboard change to Hungarian

### ISSUE THREAD

**Issue by yoursoft** [linuxmint/mint19.2-beta#15]
**Describe the bug**
Cinnamon installer keyboard change to Hungarian. 

**To Reproduce**
1. Start install
2. On select keyboard layout screen, select "Magyar" on left list.
3. Press some Hungarian keys on test input (éáű) 
4. Result some other chars (BUG 1)
5. If you click "detect keyboard layout", you will found "hungarian" layout, in the left list none selected ("Magyar" need to selected). (BUG 2)
...
6. After installation the keyboar is "English" layout, you can use the virtual keyboard to enter password.
7. In System settings / keyboard none of keyboard layout installed (empty list).  If you add "Magyar", the keyboard layout changed to "Magyar" (it is ok). But on login screen stay on English keyboard layout. (BUG 3)

**Expected behavior**
1. Start install
2. On select keyboard layout screen, select "Magyar" on left list.
3. Press some Hungarian keys on test input (éáű) 
4. Result éáű

**Frequency**
Does the issue happen:
- [X ] Always
- [ ] Randomly

**Edition (Desktop environment):**
In which edition is this happening?
- [ X] Cinnamon Edition
- [ ] MATE Edition
- [ ] Xfce Edition

**Live or post-install:**
Indicate if this is happening after the installation, or during the live session:
- [ X] Post-install
- [ ] Live session

**Locale:**
-

**Drivers:**
-

**Crash report:**
-

''Stack trace''
-

''Dmesg''
-

**Additional context**
-

**Comment by clefebvre** [comment]
I can reproduce this. I think it's a duplicated of https://github.com/linuxmint/mint19.2-beta/issues/21.
