### ISSUE TITLE
ever since installing this beta the fan on my laptop has been rattling and clicking i dont know if the new ram stuff did that or what happened ive only had the laptop for few years so its pretty new

### ISSUE THREAD

**Issue by erterine** [linuxmint/mint19.2-beta#18]
the model is Dell Inspiron E1505 if you can help figure this out as its been very loud

**Comment by erterine** [comment]
I checked and it was bought in 2006 from Currys, still it never did this before the beta

**Comment by clefebvre** [comment]
You're at the observation stage. If you find the cause of the issue and it's something we can fix, please open a new issue. https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/
