### ISSUE TITLE
cant play mjpeg videos

### ISSUE THREAD

**Issue by erterine** [linuxmint/mint19.2-beta#19]
when you download this file http://trac.ffmpeg.org/attachment/ticket/238/test.mjpeg it used to work now it dos not. i have a large folder of these videos that I can not  play now

**Comment by RavetcoFX** [comment]
I can't find any reference to mjpeg ever working, this doesn't pertain to 19.2 as I tested your file in 19.1 and it doesn't play there either. You probably had a third party codec installed before??

**Comment by clefebvre** [comment]
VLC reads them... xplayer/mpv won't. I'm not even sure xplayer likes it as a mimetype.. does that work with totem? If so, please open an issue for this on github.com/linuxmint/xplayer.
