### ISSUE TITLE
small typo in the cinnamon whatsnew beta

### ISSUE THREAD

**Issue by morton-f** [linuxmint/mint19.2-beta#2]
In The "New features in Linux Mint 19.2 Cinnnamon"
https://www.linuxmint.com/rel_tina_cinnamon_whatsnew.php
Main components: 
typo: "Mate"

**Comment by clefebvre** [comment]
Fixed, thanks @morton-f :)

**Comment by Acheron17** [comment]
There are still two present on New features in Linux Mint 19.2 Cinnamon.
https://www.linuxmint.com/rel_tina_cinnamon_whatsnew.php

See screen shot:
![Screenshot-from-2019-07-18-14-51-19](https://user-images.githubusercontent.com/45599505/61484155-4fafe380-a96c-11e9-934b-c7a3de6d9f67.png)

**Comment by clefebvre** [comment]
oopps :)
