### ISSUE TITLE
mintupdate: Consider rephrasing "Update and Restart"

### ISSUE THREAD

**Issue by kneekoo** [linuxmint/mint19.2-beta#22]
"Restart" could be misinterpreted as restarting the PC, which might put off people who can't or don't want to do that.

**Suggestions:**
Update and restart the Update Manager
Apply the update

A few questions:
- Considering the Update Manager won't update anything else before it gets updated itself, it doesn't seem like it's worth presenting the users a button to click to update+restart the Update Manager. Why not simply apply the update and inform the users about what's going on?
- Is it technically impossible for the Update Manager to update itself without restarting? Can't the UI be redrawn so that the new version can work without restarting it?

**Comment by clefebvre** [comment]
Well.. you'd need a dialog to explain what's going on, and an OK button either way. That's more or less what we have here really already.

It's possible to update the core and leave the UI alive but it's another source of error and it restricts us in what we can do with the manager. It also makes the situation more complex if we hit an issue... someone's reporting an issue with mintupdate... but he's running what? half the new one, with the previous UI? or with a UI that's 3 months old... etc.. it's not a good situation.

**Comment by clefebvre** [comment]
Fixed by https://github.com/linuxmint/mintupdate/commit/c83bd5e80d3331b8439c2ef58c051e8ede203aed.

**Comment by kneekoo** [comment]
Thanks for the fix! :)
