### ISSUE TITLE
driver manager not find my usb device

### ISSUE THREAD

**Issue by erterine** [linuxmint/mint19.2-beta#23]
this quantum crystal health analyzer i bought does not get found in the driver manager
it used to show up as firmware device but does no longer 
http://www.healthanalyzermachine.com/sale-4130983-bioelectric-mini-portable-quantum-resonance-magnetic-analyzer-with-usb-high-precision.html

**Comment by gothicVI** [comment]
Apart from the fact that USB devices do not need special drivers, you did not provide any useful debugging information. There's an issue template for a reason...

**Comment by clefebvre** [comment]
You can run "ubuntu-drivers list" to confirm that no drivers pop out for it. It doesn't look like an issue with the driver manager.
