### ISSUE TITLE
font manager is very laggy

### ISSUE THREAD

**Issue by erterine** [linuxmint/mint19.2-beta#24]
when you try and scroll or click the button the in top left there is very large ammount of delay and visible lags even when you click the search bar it is choppy

this may not be your issue I do not know let me know and I will go file a bug with whoever is more appropriate

**Comment by RavetcoFX** [comment]
What font manager are you talking about? gnome-font-viewer?

**Comment by clefebvre** [comment]
Yes, that's gnome-font-viewer. It's a pity it was redesigned.. it's upstream from us anyhow, it's part of the GNOME project.
