### ISSUE TITLE
Nemo ignores Custom settings in Root mode via (Nemo submenu "Open as Root") 

### ISSUE THREAD

**Issue by antrrax** [linuxmint/mint19.2-beta#25]
**Describe the bug**
Please, if you have a spare time, consider correcting this Nemo bug
https://github.com/linuxmint/nemo/issues/2008

Thanks

**To Reproduce**

**Expected behavior**

**Frequency**
Does the issue happen:
- [x ] Always
- [ ] Randomly

**Edition (Desktop environment):**
In which edition is this happening?
- [x ] Cinnamon Edition
- [ ] MATE Edition
- [ ] Xfce Edition

**Live or post-install:**
Indicate if this is happening after the installation, or during the live session:
- [ x] Post-install
- [ ] Live session

**Screenshots**
OK:
<a href="https://ibb.co/jZ7fZZh"><img src="https://i.ibb.co/x8VL88h/ksnip-20190717-203111.png" alt="ksnip-20190717-203111" border="0"></a>

Bug:
<a href="https://ibb.co/cbKXT8V"><img src="https://i.ibb.co/XyfkJ5M/ksnip-20190717-203521.png" alt="ksnip-20190717-203521" border="0"></a>

**Comment by corbin-auriti** [comment]
This has always been the case, its just the way Nemo works as the settings you apply to it only apply to your user, when you run as sudo, its using /root user settings. This doesn't pertain to 19.2 specifically, I would say move this issue to [github.com/linuxmint/nemo] as a feature request.
