### ISSUE TITLE
Main Cinnamon menu does not uninstall software snap

### ISSUE THREAD

**Issue by antrrax** [linuxmint/mint19.2-beta#27]
**Describe the bug**
Cinnamon menu does not uninstall software snap

**To Reproduce**
I installed a random software via snap. example: notepadqq

$ sudo apt install snapd
$ sudo snap install --classic notepadqq
restart pc

Main Cinnamon Menu > Programming > Notepadqq
Right click
Uninstall

Removes icon from Main Cinnamon Menu, but does not remove the notepadqq snap program from system.

**Expected behavior**
Full uninstall snap software from Main Cinnamon Menu, like "sudo snap remove ..."

**Frequency**
Does the issue happen:
- [ x] Always
- [ ] Randomly

**Edition (Desktop environment):**
In which edition is this happening?
- [x ] Cinnamon Edition
- [ ] MATE Edition
- [ ] Xfce Edition

**Live or post-install:**
Indicate if this is happening after the installation, or during the live session:
- [x ] Post-install
- [ ] Live session

**Screenshots**
before uninstall via Main Cinnamon Menu
<a href="https://ibb.co/1QXqNJL"><img src="https://i.ibb.co/Jtp7TFK/Screenshot-from-2019-07-17-22-40-13.png" alt="Screenshot-from-2019-07-17-22-40-13" border="0"></a>

after uninstall via Main Cinnamon Menu (Notepadqq is still installed)
<a href="https://ibb.co/x1N6MkK"><img src="https://i.ibb.co/tq9DbGw/22.png" alt="22" border="0"></a>

**Comment by clefebvre** [comment]
I think the points raised in https://blog.linuxmint.com/?p=3766 will need to be addressed before we should consider supporting snap further.
