### ISSUE TITLE
Updating system after fresh install fails. Not a crash, but a package problem.

### ISSUE THREAD

**Issue by farrinux** [linuxmint/mint19.2-beta#28]
**Describe the bug
Mint 19.2 beta - xfce desktop 32 bit system 
After initial install and reboot. running software updater fails. The updater itself seems to work, but during the update process several errors are giving on gconf package. Missing dependencies and the like.  The update is halted

**To Reproduce**
1. Install linuxmint 19.2 beta xfce 32 bit.
2. Reboot 
3. Go to software update manager. Select all packages. (Comes up that way by default.)
4. Start update. Open the details window to watch.
5. About halfway thru the process it faults out on dconf package
**Expected behavior**
completed update

**Frequency**
Does the issue happen:
- [X ] Always tried twice. Also tried through terminal same problem
- [ ] Randomly

**Edition (Desktop environment):**
In which edition is this happening?
- [ ] Cinnamon Edition
- [ ] MATE Edition
- [x ] Xfce Edition

**Live or post-install:**
Indicate if this is happening after the installation, or during the live session:
- [x ] Post-install
- [ ] Live session

**Screenshots**

**Locale:**
LANG=en_US.UTF-8
LANGUAGE=en_US
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=

**Drivers:**
Paste the output of `inxi -Gxx`.

Graphics:
  Device-1: Intel Mobile 945GSE Express Integrated Graphics 
  vendor: Acer Incorporated ALI driver: i915 v: kernel bus ID: 00:02.0 
  chip ID: 8086:27ae 
  Display: x11 server: X.Org 1.19.6 driver: intel 
  unloaded: fbdev,modesetting,vesa resolution: 1024x600~60Hz 
  OpenGL: renderer: Mesa DRI Intel 945GME x86/MMX/SSE2 v: 1.4 Mesa 19.0.2 
  direct render: Yes 

**Crash report:**

''Stack trace''
If you are reporting a crash. Go to "Software Sources" and enable the debug symbols. Then go to "System Reports" and extract the stack trace for your crash and paste it here.

''Dmesg''
If you type `dmesg` in a terminal, you should see a line corresponding to the crash. Paste it here.

**Additional context**

**Comment by gothicVI** [comment]
Given you tried it via the terminal it might be helpful to paste/link the output or at least a screen shot. How are the devs supposed to know which packages might cause a failure?

**Comment by monsta** [comment]
> during the update process several errors are giving on gconf package

Known upstream (Ubuntu) issue, not a Mint one. Reported numerous times on the forums, and also at https://github.com/linuxmint/mintupdate/issues/552. Upstream report is [here](https://bugs.launchpad.net/bugs/1551623). I've sent them patches for gconf, but actually it might be fixed soon in another way - by patching dpkg. That is tracked at another upstream report [here](https://bugs.launchpad.net/bugs/1828639).
