### ISSUE TITLE
Can't edit Mate menu preferences

### ISSUE THREAD

**Issue by rebelxt** [linuxmint/mint19.2-beta#3]
**Describe the bug**
Can't edit Mate menu preferences

**To Reproduce**
1. Right-click on the menu icon in the panel.
2. Click on Preferences.
3. Nothing happens.

**Expected behavior**
Should see the Menu Preferences dialog.

**Frequency**
Does the issue happen:
- [X ] Always
- [ ] Randomly

**Edition (Desktop environment):**
In which edition is this happening?
- [ ] Cinnamon Edition
- [X ] MATE Edition
- [ ] Xfce Edition

**Live or post-install:**
Indicate if this is happening after the installation, or during the live session:
- [X ] Post-install
- [ X] Live session

**Screenshots**

**Locale:**
LANG=en_US.UTF-8
LANGUAGE=en_US
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=

**Drivers:**
Graphics:
  Device-1: InnoTek Systemberatung VirtualBox Graphics Adapter 
  driver: vboxvideo v: kernel bus ID: 00:02.0 chip ID: 80ee:beef 
  Display: x11 server: X.Org 1.19.6 driver: modesetting unloaded: fbdev,vesa 
  alternate: vboxvideo compositor: marco resolution: 1920x1080~60Hz 
  OpenGL: renderer: llvmpipe (LLVM 8.0 256 bits) v: 3.3 Mesa 19.0.2 
  compat-v: 3.1 direct render: Yes 

**Crash report:**

''Stack trace''
If you are reporting a crash. Go to "Software Sources" and enable the debug symbols. Then go to "System Reports" and extract the stack trace for your crash and paste it here.

''Dmesg''
If you type `dmesg` in a terminal, you should see a line corresponding to the crash. Paste it here.

**Additional context**
This documentation is from a VirtualBox install, but I have seen the problem on a hard-drive install, although that was an older (maybe unofficial) beta.

From the terminal:
/usr/lib/linuxmint/mintMenu/preferences.py
gives message:
ModuleNotFoundError: No module named 'Xlib'

**Comment by clefebvre** [comment]
Fixed in mintmenu 5.9.4 (https://github.com/linuxmint/mintmenu/commit/2419c9d36cd4f07b9a48cd030685cc498f388653)
