### ISSUE TITLE
Nemo: German translation for pin/unpin wrong

### ISSUE THREAD

**Issue by Mintulix** [linuxmint/mint19.2-beta#30]
NOTE: copied from apha-testing, because Clem mentioned, those issues won't be traced anymore. Alpha is a real install / update from 19.1, I think the error must be in beta, too, but I didn't install it (and the live-version is just in English), so it's just a suggestion:

choose German language (perhaps other languages, too?)
log off and on again
open nemo
right click on any file
->
pin and unpin are interchanged

IS:
pin - lösen
unpin - anheften

SHOULD BE:
pin - anheften
unpin - lösen

**Frequency**
Does the issue happen:
- [x] Always
- [ ] Randomly

**Edition (Desktop environment):**
In which edition is this happening?
- [x] Cinnamon Edition
- [ ] MATE Edition
- [ ] Xfce Edition

**Live or post-install:**
Indicate if this is happening after the installation, or during the live session:
- [x] Post-install in alpha!
- [ ] Live session

**Locale:**
Paste the output of `locale`.
de_DE.UTF-8

**Comment by kelebek333** [comment]
You can edit on Launhpad.

[https://translations.launchpad.net/linuxmint/latest/+pots/nemo/de/382/+translate](https://translations.launchpad.net/linuxmint/latest/+pots/nemo/de/382/+translate)
[https://translations.launchpad.net/linuxmint/latest/+pots/nemo/de/381/+translate](https://translations.launchpad.net/linuxmint/latest/+pots/nemo/de/381/+translate)

**Comment by Mintulix** [comment]
Thanks. I searched it there, but didn't found it (because of the underscores).
Now it's corrected, it just has to be applied sometime.
