### ISSUE TITLE
cinnamon-screensaver: slow performance

### ISSUE THREAD

**Issue by VaGNaroK** [linuxmint/mint19.2-beta#35]
**Hardware**
https://pastebin.com/raw/JSyTXLTU

**Describe the bug**
When it blocks the screen and goes to the login manager, clicking on the password field is very slow to exit the digits.

**To Reproduce**
1. Go to 'Menu'
2. Click on 'lock screen'
3. wait a few seconds and try typing your unlock password.

**Expected behavior**
slowness when exiting the digits in the password field.

**Frequency**
Does the issue happen:
- [X] Always
- [ ] Randomly

**Edition (Desktop environment):**
In which edition is this happening?
- [X] Cinnamon Edition
- [ ] MATE Edition
- [ ] Xfce Edition

**Locale:**
Paste the output of `PT-BR`.

**Drivers:**
Paste the output of `inxi -Gxx`.
Graphics:
  Device-1: NVIDIA G96 [GeForce 9500 GT] vendor: eVga.com. driver: nouveau 
  v: kernel bus ID: 01:00.0 chip ID: 10de:0640 
  Display: x11 server: X.Org 1.19.6 driver: nouveau 
  unloaded: fbdev,modesetting,vesa resolution: 1366x768~60Hz 
  OpenGL: renderer: NV96 v: 3.3 Mesa 19.0.2 direct render: Yes 

''Dmesg''

https://pastebin.com/raw/g5BAxVwj

**Comment by LinuxOnTheDesktop** [comment]
Perhaps it will be useful to note that this was [reported in the alpha testing and believed fixed](https://github.com/linuxmint/alpha-testing/issues/10).

**Comment by VaGNaroK** [comment]
> Perhaps it will be useful to note that this was [reported in the alpha testing and believed fixed](https://github.com/linuxmint/alpha-testing/issues/10).

It's like you said. More on the day I quereportei was having this slow login problem. But now (1 day later), I did the same tests and the problem is no longer occurring. I do not know if it was any update. But the login manager is normal now. Should I remove the issue repport?

**Comment by LinuxOnTheDesktop** [comment]
Do you mean the following? On the beta, you had the problem but then (still on the beta) the problem went away. If that is what you mean, then I think you should leave this report. For, ideally, the problem should not occur even initially.

**Comment by VaGNaroK** [comment]
> Do you mean the following? On the beta, you had the problem but then (still on the beta) the problem went away. If that is what you mean, then I think you should leave this report. For, ideally, the problem should not occur even initially.

Exactly what happened! the problem in the login manager was even me restarting the pc and so on. had some package updates from the official repository from yesterday to today and I do not know if that was what it solved. But today the problem no longer exists. I do not know what happened.

**Comment by clefebvre** [comment]
I think we fixed that prior to BETA. I'll close this here but we'll keep an eye on it going forward.
