### ISSUE TITLE
resize Startup Applications Preferences window problem

### ISSUE THREAD

**Issue by rebelxt** [linuxmint/mint19.2-beta#37]
**Describe the bug**
In Startup Applications Preferences, when the window is resized, the list of programs does not resize with the window.

**To Reproduce**
1. Launch: Startup Applications Preferences
2. Resize the window (make it larger)

**Expected behavior**
The widget containing the program list should also grow.

**Frequency**
Does the issue happen:
- [X] Always
- [ ] Randomly

**Edition (Desktop environment):**
In which edition is this happening?
- [ ] Cinnamon Edition
- [X] MATE Edition
- [ ] Xfce Edition

**Live or post-install:**
Indicate if this is happening after the installation, or during the live session:
- [X] Post-install
- [ ] Live session

**Screenshots**
![Screenshot at 2019-07-19 09-00-19](https://user-images.githubusercontent.com/2348129/61537294-c993ab80-aa04-11e9-88f0-a4a2533b5152.png)

**Locale:**
LANG=en_US.UTF-8
LANGUAGE=en_US
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=

**Drivers:**
Graphics:
  Device-1: Intel Xeon E3-1200 v2/3rd Gen Core processor Graphics 
  vendor: ASUSTeK P8H77-I driver: i915 v: kernel bus ID: 00:02.0 
  chip ID: 8086:0152 
  Display: x11 server: X.Org 1.19.6 driver: modesetting unloaded: fbdev,vesa 
  compositor: marco resolution: 1920x1080~60Hz, 1920x1080~60Hz 
  OpenGL: renderer: Mesa DRI Intel Ivybridge Desktop v: 4.2 Mesa 19.0.2 
  compat-v: 3.0 direct render: Yes 

**Crash report:**

''Stack trace''
If you are reporting a crash. Go to "Software Sources" and enable the debug symbols. Then go to "System Reports" and extract the stack trace for your crash and paste it here.

''Dmesg''
If you type `dmesg` in a terminal, you should see a line corresponding to the crash. Paste it here.

**Additional context**

**Comment by gm10** [comment]
I already fixed that upstream: https://github.com/mate-desktop/mate-session-manager/commit/66b4795d5e0a14c845c6cd5d00ff0644ac1cdeb3.
