### ISSUE TITLE
The problem of opening a mp3 file in the media player by default, if you open more mp3 files remains blocked by the hourglass waiting ...

### ISSUE THREAD

**Issue by ruldc** [linuxmint/mint19.2-beta#38]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Frequency**
Does the issue happen:
- [ ] Always
- [ ] Randomly

**Edition (Desktop environment):**
In which edition is this happening?
- [ ] Cinnamon Edition
- [ ] MATE Edition
- [ ] Xfce Edition

**Live or post-install:**
Indicate if this is happening after the installation, or during the live session:
- [ ] Post-install
- [ ] Live session

**Screenshots**

**Locale:**
Paste the output of `locale`.

**Drivers:**
Paste the output of `inxi -Gxx`.

**Crash report:**

''Stack trace''
If you are reporting a crash. Go to "Software Sources" and enable the debug symbols. Then go to "System Reports" and extract the stack trace for your crash and paste it here.

''Dmesg''
If you type `dmesg` in a terminal, you should see a line corresponding to the crash. Paste it here.

**Additional context**

**Comment by clefebvre** [comment]
That's an observation not a bug report.
