### ISSUE TITLE
eric (python ide) not working after install

### ISSUE THREAD

**Issue by orcus-de** [linuxmint/mint19.2-beta#41]
**Describe the bug**
using  installed  + 19.2 cinnamon 64bit beta    qemu/kvm vm Installed without additional codecs fully updated   2019-07-20  ninja-ide not working after installation

eric (python ide) not working after install

**To Reproduce**
1. Install eric via software-manager
2. launche via menu
3. only the splash-screen get's displayed

running eric from a terminal does return:
oadm@mint-19-2-cinnamon-64bit-beta:~$ eric
qt5ct: using qt5ct plugin
Warning: translation file 'qt_en_US'could not be loaded.
Using default.
Warning: translation file 'qscintilla_en_US'could not be loaded.
Using default.
BackgroundService listening on: 44445
An unhandled exception occurred. Please report the problem
using the error reporting dialog or via email to <eric-bugs@eric-ide.python-projects.org>.
A log has been written to "/home/oadm/.eric6/eric6_error.log".

Error information:
--------------------------------------------------------------------------------
2019-07-20, 01:03:39
--------------------------------------------------------------------------------
<class 'ModuleNotFoundError'>: 
No module named 'distutils.sysconfig'
--------------------------------------------------------------------------------
  File "/usr/share/eric/modules/eric6.py", line 379, in <module>
    main()
  File "/usr/share/eric/modules/eric6.py", line 360, in main
    disablecrash, restartArgs)
  File "/usr/share/eric/modules/UI/UserInterface.py", line 248, in __init__
    self.pluginManager = PluginManager(self, develPlugin=plugin)
  File "/usr/share/eric/modules/PluginManager/PluginManager.py", line 98, in __init__
    "global": os.path.join(Utilities.getPythonModulesDirectory(),
  File "/usr/share/eric/modules/Globals/__init__.py", line 108, in getPythonModulesDirectory
    import distutils.sysconfig

--------------------------------------------------------------------------------
Version Numbers:
  Python 3.6.8
  Qt 5.9.5
  PyQt 5.10.1
  sip 4.19.7
  QScintilla 2.10.2
  WebKit 602.1
  eric6 17.11.1 (rev. ab851fd69434)

Platform: linux
3.6.8 (default, Jan 14 2019, 11:02:34) 
[GCC 8.0.1 20180414 (experimental) [trunk revision 259383]]
--------------------------------------------------------------------------------
Distribution Info:
  /etc/lsb-release
  DISTRIB_ID=LinuxMint
  DISTRIB_RELEASE=19.2
  DISTRIB_CODENAME=tina
  DISTRIB_DESCRIPTION="Linux Mint 19.2 Tina"

  /etc/os-release
  NAME="Linux Mint"
  VERSION="19.2 (Tina)"
  ID=linuxmint
  ID_LIKE=ubuntu
  PRETTY_NAME="Linux Mint 19.2"
  VERSION_ID="19.2"
  HOME_URL="https://www.linuxmint.com/"
  SUPPORT_URL="https://forums.ubuntu.com/"
  BUG_REPORT_URL="http://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/"
  PRIVACY_POLICY_URL="https://www.linuxmint.com/"
  VERSION_CODENAME=tina
  UBUNTU_CODENAME=bionic

**Expected behavior**
Eric should work after installation
required dependencies should be resolved

**Frequency**
Does the issue happen:
- [x] Always
- [ ] Randomly

**Edition (Desktop environment):**
In which edition is this happening?
- [x] Cinnamon Edition
- [ ] MATE Edition
- [ ] Xfce Edition

**Live or post-install:**
Indicate if this is happening after the installation, or during the live session:
- [x] Post-install
- [ ] Live session

**Screenshots**

**Locale:**
Paste the output of `locale`.

**Drivers:**
Paste the output of `inxi -Gxx`.

**Crash report:**

''Stack trace''
If you are reporting a crash. Go to "Software Sources" and enable the debug symbols. Then go to "System Reports" and extract the stack trace for your crash and paste it here.

''Dmesg''
If you type `dmesg` in a terminal, you should see a line corresponding to the crash. Paste it here.

**Additional context**

**Comment by clefebvre** [comment]
Upstream: 

Fixed in Debian, https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=903717
Pending in Ubuntu, https://bugs.launchpad.net/ubuntu/+source/eric/+bug/1794186
