### ISSUE TITLE
installing nodejs

### ISSUE THREAD

**Issue by apurva04** [linuxmint/mint19.2-beta#42]
**Describe the bug**
i tried to install node js on linux mint 19.2 cinnamon but it says 

Your distribution, identified as "tina", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support

**To Reproduce**
 folow this step to install latest node js version
**Expected behavior**
node js must be installed

**Frequency**
Does the issue happen:
-  Always

**Edition (Desktop environment):**
In which edition is this happening?
- Cinnamon Edition
**Live or post-install:**
Indicate if this is happening after the installation, or during the live session:
-  Post-install

**Screenshots**

**Locale:**
Paste the output of `locale`.

**Drivers:**
Paste the output of `inxi -Gxx`.
 Device-1: AMD Mullins [Radeon R3 Graphics] vendor: Acer Incorporated ALI 
  driver: radeon v: kernel bus ID: 00:01.0 chip ID: 1002:9850 
  Display: x11 server: X.Org 1.19.6 driver: ati,radeon 
  unloaded: fbdev,modesetting,vesa resolution: 1366x768~60Hz 
  OpenGL: renderer: AMD MULLINS (DRM 2.50.0 4.15.0-54-generic LLVM 8.0.0) 
  v: 4.5 Mesa 19.0.2 direct render: Yes

**Crash report:**

''Stack trace''
If you are reporting a crash. Go to "Software Sources" and enable the debug symbols. Then go to "System Reports" and extract the stack trace for your crash and paste it here.

''Dmesg''
If you type `dmesg` in a terminal, you should see a line corresponding to the crash. Paste it here.

**Additional context**

**Comment by clefebvre** [comment]
Thanks, reported upstream: https://github.com/nodesource/distributions/pull/876.

**Comment by apurva04** [comment]
@clefebvre I tried again but it still says 

Your distribution, identified as "tina", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support

is the issue resolved?

**Comment by clefebvre** [comment]
We made the PR I linked to. It's up to nodejs to accept it or not. As it is now it's open. They'll either close it or merge it. That's up to them though.
