### ISSUE TITLE
Firefox profile copy difficulty

### ISSUE THREAD

**Issue by rebelxt** [linuxmint/mint19.2-beta#45]
**Describe the bug**
After copying the Firefox profile from Mint 18.3, this error occurs when launching Firefox:

![Firefox msg](https://user-images.githubusercontent.com/2348129/61579863-cf5ac100-aad8-11e9-9b54-ffc98cc139d5.png)

**To Reproduce**
1. Copy the ~/.mozilla/firefox folder from Mint Mate 18.3 to Mint Mate 19.2
2. Launch Firefox
3. See error

**Expected behavior**
Firefox should start normally, as this is not actually an older version.

**Frequency**
Does the issue happen:
- [x] Always
- [ ] Randomly

**Edition (Desktop environment):**
In which edition is this happening?
- [ ] Cinnamon Edition
- [x] MATE Edition
- [ ] Xfce Edition

**Live or post-install:**
Indicate if this is happening after the installation, or during the live session:
- [x] Post-install
- [ ] Live session

**Screenshots**

**Locale:**
Paste the output of `locale`.

**Drivers:**
Paste the output of `inxi -Gxx`.

**Crash report:**

''Stack trace''
If you are reporting a crash. Go to "Software Sources" and enable the debug symbols. Then go to "System Reports" and extract the stack trace for your crash and paste it here.

''Dmesg''
If you type `dmesg` in a terminal, you should see a line corresponding to the crash. Paste it here.

**Additional context**
Firefox version in Mint Mate 19.2: 68.0+linuxmint1+tessa
Firefox version in Mint Mate 18.3: 68.0+linuxmint1+sylvia

I'm reporting this in Mint Mate beta, but I suspect it would also happen in Mint Cinnamon.

I don't know if this can actually be considered a bug, or if there is anything that can be done about it, but it seemed to be worth reporting. I also know there are other ways to accomplish this, but for me, it's the easiest.

Edit:
Is this because of the way the Firefox versions are named? Copying the Thunderbird profile works.

Thunderbird version in Mint Mate 19.2:  1:60.8.0+build1-0ubuntu0.18.04.1
Thunderbird version in Mint Mate 18.3:  1:60.7.2+build2-0ubuntu0.16.04.1

**Comment by clefebvre** [comment]
This is a bit weird.. the version should be considered the same. Either way, this is upstream from us.

**Comment by rebelxt** [comment]
After some more searching, I discovered the firefox --allow-downgrade option overrides the version check. Now I will have to be very careful with future Firefox updates.
