### ISSUE TITLE
Application menu can not see the difference between app and app from flatpak

### ISSUE THREAD

**Issue by kacperpaczos** [linuxmint/mint19.2-beta#47]
**Describe the bug**
Application menu can not see the difference between app and app from flatpak

**To Reproduce**
Try to open graphics file by use another program, using context menu.

**Expected behavior**
I should can see difference between flatpak and non-flatpak version of the program

**Frequency**
Does the issue happen:
- [*] Always
- [ ] Randomly

**Edition (Desktop environment):**
In which edition is this happening?
- [*] Cinnamon Edition
- [ ] MATE Edition
- [ ] Xfce Edition

**Live or post-install:**
Indicate if this is happening after the installation, or during the live session:
- [*] Post-install
- [ ] Live session

**Screenshots**
![obraz](https://user-images.githubusercontent.com/23406555/61580743-71989a00-ab15-11e9-89b1-752ff7d728d9.png)
![obraz](https://user-images.githubusercontent.com/23406555/61580746-76f5e480-ab15-11e9-8c3d-2405b8a2e1fb.png)
![obraz](https://user-images.githubusercontent.com/23406555/61580747-78bfa800-ab15-11e9-8aea-6490f158010c.png)
![obraz](https://user-images.githubusercontent.com/23406555/61580749-7bba9880-ab15-11e9-8691-62008910b3b7.png)

**Locale:**
Paste the output of `locale`.
LANG=pl_PL.UTF-8
LANGUAGE=pl
LC_CTYPE="pl_PL.UTF-8"
LC_NUMERIC="pl_PL.UTF-8"
LC_TIME="pl_PL.UTF-8"
LC_COLLATE="pl_PL.UTF-8"
LC_MONETARY="pl_PL.UTF-8"
LC_MESSAGES="pl_PL.UTF-8"
LC_PAPER="pl_PL.UTF-8"
LC_NAME="pl_PL.UTF-8"
LC_ADDRESS="pl_PL.UTF-8"
LC_TELEPHONE="pl_PL.UTF-8"
LC_MEASUREMENT="pl_PL.UTF-8"
LC_IDENTIFICATION="pl_PL.UTF-8"
LC_ALL=
**Drivers:**
Paste the output of `inxi -Gxx`.

**Crash report:**

''Stack trace''
If you are reporting a crash. Go to "Software Sources" and enable the debug symbols. Then go to "System Reports" and extract the stack trace for your crash and paste it here.

''Dmesg''
If you type `dmesg` in a terminal, you should see a line corresponding to the crash. Paste it here.

**Additional context**
The same problem with another applications, like LibreOffice.

**Comment by clefebvre** [comment]
There's no support for duplicates in nemo, that's normal..

For the cinnamon menu though, I can reproduce the issue.

**Comment by clefebvre** [comment]
![Screenshot from 2019-07-23 06-33-47](https://user-images.githubusercontent.com/1138515/61712602-f6262b00-ad56-11e9-8396-72fd75a7cab2.png)

We can't reproduce this issue in 19.2.
