### ISSUE TITLE
Button 'Toggle location entry' vs Xapps dialog box

### ISSUE THREAD

**Issue by antrrax** [linuxmint/mint19.2-beta#5]
**Describe the bug**
Xapps dialog box does not provide an intuitive option to edit the location bar
Dialogs: Open Files and Save As... 

**To Reproduce**
<a href="https://ibb.co/gtPK3h8"><img src="https://i.ibb.co/gtPK3h8/ksnip-20190716-222017.png" alt="ksnip-20190716-222017" border="0"></a>

**Expected behavior**
To display the location bar, I have to type the "/"
If I already have a full path ("/home/beta/Desktop") in the clipboard and paste it into the location bar I get two bars ("**//**home/beta/Desktop") at the beginning of the path.

The correct one, would be to have the button "Toggle location entry" like the one that exists in Nemo.
<a href="https://ibb.co/FsY2XY1"><img src="https://i.ibb.co/9w46h40/Screenshot-from-2019-07-16-22-24-28.png" alt="Screenshot-from-2019-07-16-22-24-28" border="0"></a>

**Frequency**
Does the issue happen:
- [x ] Always
- [ ] Randomly

**Edition (Desktop environment):**
In which edition is this happening?
- [x ] Cinnamon Edition
- [ ] MATE Edition
- [ ] Xfce Edition

**Live or post-install:**
Indicate if this is happening after the installation, or during the live session:
- [x ] Post-install
- [ ] Live session

**Comment by JosephMcc** [comment]
This has been brought up many times. This is an issue with the Gtk Dialog and has been reported to them by others. This has nothing to do with us and we cannot control it.

**Comment by clefebvre** [comment]
It's ok to have // instead of / afaik, though that's beside the point.

GTK uses Ctrl+L to toggle the path bar into an entry. It's not very discoverable and if I remember right they used to have a toggle button in GTK2 and it was removed.

Either way, I'd recommend to use Ctrl+L for this, and to check with them directly to see if they're open to adding a button or not.
