### ISSUE TITLE
Cancel is not translated in French

### ISSUE THREAD

**Issue by InfoLibre** [linuxmint/mint19.2-beta#50]
There are some windows where the "Cancel" button is not translated in French (should be "Annuler" instead of "Cancel").
Examples :
![Langue_2](https://user-images.githubusercontent.com/3955499/61582084-8cbfd580-ab26-11e9-8fba-c0ce4777ec2d.png)
![Langue_5](https://user-images.githubusercontent.com/3955499/61582087-90535c80-ab26-11e9-9bf3-9f3eb0d69e56.png)
![Synaptic_2](https://user-images.githubusercontent.com/3955499/61582089-92b5b680-ab26-11e9-9d98-623ec6eece8f.png)

**Comment by clefebvre** [comment]
Run mintlocale and check that support for French is complete. It looks like you're missing language packs.

**Comment by InfoLibre** [comment]
Indeed, sorry for the trouble.
