### ISSUE TITLE
Ubiquity: Multiple wrong Finnish translations

### ISSUE THREAD

**Issue by corefx** [linuxmint/mint19.2-beta#51]
**Describe the bug**
There are multiple wrong Finnish translations in Ubiquity.

#. Type: text
#. Description
#. RELEASE is a variable substituted into this string, and may be 'Linux Mint'
#: ../ubiquity.templates:104001
msgid ""
"Installation has finished.  You can continue testing ${RELEASE} now, but "
"until you restart the computer, any changes you make or documents you save "
"will not be preserved."
msgstr ""
"Asennus on valmis. Voit jatkaa ${RELEASE}n kokeilua, mutta mitkään tekemäsi "
"muutokset tai asiakirjat eivät säily, ennen kuin käynnistät koneen uudelleen."

Correct translation: ${RELEASE}in

#. Type: text
#. Description
#. DISTRO is a variable substituted into this string, and may be 'Linux Mint'
#: ../ubiquity.templates:248001
msgid ""
"You can create or resize partitions yourself, or choose multiple partitions "
"for ${DISTRO}."
msgstr ""
"Voit luoda tai muuttaa osioiden kokoja itse, tai valita useita osioita "
"${DISTRO}n käytettäväksi."

Correct translation: ${DISTRO}in

#. Type: text
#. Description
#. RELEASE is a variable substituted into this string, and may be 'Linux Mint'
#: ../ubiquity.templates:11001
msgid "Try ${RELEASE}"
msgstr "Kokeile ${RELEASE}a"

Correct translation: ${RELEASE}iä

#. Type: text
#. Description
#. RELEASE is a variable substituted into this string, and may be 'Linux Mint'
#: ../ubiquity.templates:10001
msgid ""
"Or if you're ready, you can install ${RELEASE} alongside (or instead of) "
"your current operating system.  This shouldn't take too long."
msgstr ""
"Jos olet valmis, voit asentaa ${RELEASE}n nykyisen käyttöjärjestelmäsi "
"rinnalle tai tilalle. Asentaminen ei kestä kauan."

Correct translation: ${RELEASE}in

#. Type: text
#. Description
#. RELEASE is a variable substituted into this string, and may be 'Linux Mint'
#. MEDIUM is a variable substituted into this string, and may be 'CD'
#: ../ubiquity.templates:10001
msgid ""
"You can try ${RELEASE} without making any changes to your computer, directly "
"from this ${MEDIUM}."
msgstr ""
"Voit kokeilla ${RELEASE}a suoraan tältä ${MEDIUM}-tallennusvälineeltä "
"tekemättä muutoksia tietokoneellesi."

Correct translation: ${RELEASE}iä

**To Reproduce**
Install Linux Mint 19.2 Beta. (I used the Cinnamon version)

**Expected behavior**
No wrong translations.

**Frequency**
Does the issue happen:
- [x] Always
- [ ] Randomly

**Edition (Desktop environment):**
In which edition is this happening?
- [x] Cinnamon Edition
- [x] MATE Edition
- [x] Xfce Edition

**Live or post-install:**
Indicate if this is happening after the installation, or during the live session:
- [ ] Post-install
- [x] Live session

**Screenshots**

**Locale:**
Paste the output of `locale`.

**Drivers:**
Paste the output of `inxi -Gxx`.

**Crash report:**

''Stack trace''
If you are reporting a crash. Go to "Software Sources" and enable the debug symbols. Then go to "System Reports" and extract the stack trace for your crash and paste it here.

''Dmesg''
If you type `dmesg` in a terminal, you should see a line corresponding to the crash. Paste it here.

**Additional context**

**Comment by NikoKrause** [comment]
Please fix those translations here https://translations.launchpad.net/ubuntu/eoan/+source/ubiquity/+pots/ubiquity-debconf/fi/+translate

**Comment by corefx** [comment]
Hello,
Only Mint translations have these wrong inflections. Ubuntu translations are fine.

**Comment by clefebvre** [comment]
Is it because "Linux Mint" finishes with a t and "Ubuntu" finishes with a vowel?

**Comment by corefx** [comment]
Yes, (in reality it's more complex).

**Comment by clefebvre** [comment]
@corefx are you familiar with git? Could you implement these changes as a pull request against https://github.com/linuxmint/ubiquity?

I can do it myself if you don't feel confident about using git. Just let me know.

**Comment by corefx** [comment]
Done. [https://github.com/linuxmint/ubiquity/pull/44](url)

**Comment by clefebvre** [comment]
Excellent. Many thanks for your help @corefx !
