### ISSUE TITLE
Shutter opens Pinta after a capture but the capture doesn't appear in Pinta

### ISSUE THREAD

**Issue by InfoLibre** [linuxmint/mint19.2-beta#53]
**Describe the bug**
Shutter opens Pinta after a capture but the capture doesn't appear in Pinta

**To Reproduce**
1.Install Shutter and Pinta : sudo apt install shutter pinta
2. Start Shutter
3. In Shutter, go to menu Preferences - Actions and set Pinta as default picture editor
![Capture du 2019-07-21 12-45-42](https://user-images.githubusercontent.com/3955499/61590239-136fc380-abb6-11e9-849e-175a4d8e8ec8.png)
4. Take a zone capture with shutter. Pinta starts

**Expected behavior**
The capture should appear in Pinta but Pinta is empty :
![Capture du 2019-07-21 12-46-43](https://user-images.githubusercontent.com/3955499/61590247-38fccd00-abb6-11e9-8729-3829448ce7cb.png)

**Frequency**
Does the issue happen:
- [X ] Always
- [ ] Randomly

**Edition (Desktop environment):**
In which edition is this happening?
- [ ] Cinnamon Edition
- [X] MATE Edition
- [ ] Xfce Edition

**Live or post-install:**
Indicate if this is happening after the installation, or during the live session:
- [X] Post-install
- [] Live session

**Locale:**
LANG=fr_FR.UTF-8
LANGUAGE=fr_FR
LC_CTYPE="fr_FR.UTF-8"
LC_NUMERIC="fr_FR.UTF-8"
LC_TIME="fr_FR.UTF-8"
LC_COLLATE="fr_FR.UTF-8"
LC_MONETARY="fr_FR.UTF-8"
LC_MESSAGES="fr_FR.UTF-8"
LC_PAPER="fr_FR.UTF-8"
LC_NAME="fr_FR.UTF-8"
LC_ADDRESS="fr_FR.UTF-8"
LC_TELEPHONE="fr_FR.UTF-8"
LC_MEASUREMENT="fr_FR.UTF-8"
LC_IDENTIFICATION="fr_FR.UTF-8"
LC_ALL=

**Drivers:**
Paste the output of `inxi -Gxx`.
Graphics:  Device-1: NVIDIA GK107GL [Quadro K2000] vendor: Hewlett-Packard driver: nouveau v: kernel 
           bus ID: 05:00.0 chip ID: 10de:0ffe 
           Display: x11 server: X.Org 1.19.6 driver: nouveau unloaded: fbdev,modesetting,vesa 
           compositor: marco resolution: 1920x1080~60Hz 
           OpenGL: renderer: NVE7 v: 4.3 Mesa 19.0.2 direct render: Yes

**Additional context**
When I use Shutter with Pix, Firefox or Gimp instead of Pinta, it works well. The bug is only with Pinta.

**Comment by kacperpaczos** [comment]
All work fine exept for pinta.
My log:
First test for pinta: fail;

> INFO: new upload-plugin information detected - /usr/share/shutter/resources/system/upload_plugins/upload/vgyme
> Unescaped left brace in regex is illegal here in regex; marked by <-- HERE in m/^<.*>\n{ <-- HERE / at /usr/share/shutter/resources/system/upload_plugins/upload/vgyme.pm line 159.
> 
> ERROR: upload-plugin exists but does not work properly - /usr/share/shutter/resources/system/upload_plugins/upload/vgyme
> Current window manager: Mutter (Muffin)
> Current window manager: Mutter (Muffin)
> Current window manager: Mutter (Muffin)
> Current window manager: Mutter (Muffin)
> 
> type_changed was emitted by widget Gtk2::ComboBox=HASH(0x55c5fe9da5f8)
> 
> im_colors_changed was emitted by widget Gtk2::ComboBox=HASH(0x55c601938450)
> 
> im_colors_toggled was emitted by widget Gtk2::CheckButton=HASH(0x55c601938498)
> 
> thumbnail_changed was emitted by widget Gtk2::HScale=HASH(0x55c601938558)
> 
> thumbnail_toggled was emitted by widget Gtk2::CheckButton=HASH(0x55c601938510)
> 
> bordereffect_toggled was emitted by widget Gtk2::CheckButton=HASH(0x55c601938648)
> 
> bordereffect_changed was emitted by widget Gtk2::SpinButton=HASH(0x55c601938660)
> 
> menu_delay_changed was emitted by widget Gtk2::SpinButton=HASH(0x55c6019d4860)
> 
> hide_time_changed was emitted by widget Gtk2::SpinButton=HASH(0x55c6019d4e30)
> 
> ns_changed was emitted by widget Gtk2::ComboBox=HASH(0x55c6019d4ed8)
> 
> fct_update_tray_menu was called by Gnome2::Wnck::Screen=HASH(0x55c600bcd548)
> Updating fileinfos for key: [1] - Zaznaczenie_001.png
> file:///home/pyroxar/Obrazy/Zaznaczenie_001.png thumbnail already exists
> file:///home/pyroxar/Obrazy/Zaznaczenie_001.png thumbnail already exists
> Updating fileinfos for key: [2] - Zaznaczenie_002.png
> file:///home/pyroxar/Obrazy/Zaznaczenie_002.png thumbnail already exists
> file:///home/pyroxar/Obrazy/Zaznaczenie_002.png thumbnail already exists
> Updating fileinfos for key: [3] - Zaznaczenie_003.png
> file:///home/pyroxar/Obrazy/Zaznaczenie_003.png thumbnail already exists
> file:///home/pyroxar/Obrazy/Zaznaczenie_003.png thumbnail already exists
> Updating fileinfos for key: [4] - Zaznaczenie_004.png
> file:///home/pyroxar/Obrazy/Zaznaczenie_004.png thumbnail already exists
> file:///home/pyroxar/Obrazy/Zaznaczenie_004.png thumbnail already exists
> GdkPixbuf-LOG **: gdk_pixbuf_from_pixdata() called on: at /usr/bin/shutter line 2891.
> GdkPixbuf-LOG **: 	Encoding raw at /usr/bin/shutter line 2891.
> GdkPixbuf-LOG **: 	Dimensions: 16 x 16 at /usr/bin/shutter line 2891.
> GdkPixbuf-LOG **: 	Rowstride: 64, Length: 1048 at /usr/bin/shutter line 2891.
> GdkPixbuf-LOG **: 	Copy pixels == false at /usr/bin/shutter line 2891.
> GdkPixbuf-LOG **: gdk_pixbuf_from_pixdata() called on: at /usr/bin/shutter line 2891.
> GdkPixbuf-LOG **: 	Encoding raw at /usr/bin/shutter line 2891.
> GdkPixbuf-LOG **: 	Dimensions: 16 x 16 at /usr/bin/shutter line 2891.
> GdkPixbuf-LOG **: 	Rowstride: 64, Length: 1048 at /usr/bin/shutter line 2891.
> GdkPixbuf-LOG **: 	Copy pixels == false at /usr/bin/shutter line 2891.
> 
> fct_update_tray_menu was called by Gnome2::Wnck::Screen=HASH(0x55c600bcd548)
> 
> select was emitted by widget Gtk2::ToolButton=HASH(0x55c5fea3eb40)
> 3 Ns used in wild-card
> Searching for files with pattern: (?^u:\$name_(\d\d\d)\.png)
> Searching for files with pattern: (?^u:.{1,}_(\d\d\d)\.png)
> Comparing d4.png
> Comparing Zaznaczenie_003.png
> 003 is currently greatest value...
> Comparing d1.png
> Comparing d2.png
> Comparing Richard Stallman - We're heading for a total disaster-uFMMXRoSxnA.webm
> Comparing Zaznaczenie_004.png
> 004 is currently greatest value...
> Comparing Zaznaczenie_002.png
> Comparing d3.png
> Comparing Zaznaczenie_001.png
> Comparing Zrzut ekranu z 2019-07-19 21-54-46.png
> Using monitor: 0 - 0 - 1920 - 1080
> Parsing wildcards for /home/pyroxar/Obrazy/$name_005.png
> Parsed $width and $height: /home/pyroxar/Obrazy/$name_005.png
> Parsed $profile: /home/pyroxar/Obrazy/$name_005.png
> Parsed $name: /home/pyroxar/Obrazy/Zaznaczenie_005.png
> New uri after exists check: file:///home/pyroxar/Obrazy/Zaznaczenie_005.png
> Trying to save file to /home/pyroxar/Obrazy/Zaznaczenie_005.png
> Saving file /home/pyroxar/Obrazy/Zaznaczenie_005.png, png, 9
> Updating fileinfos for key: [5] - Zaznaczenie_005.png
> file:///home/pyroxar/Obrazy/Zaznaczenie_005.png thumbnail created
> file:///home/pyroxar/Obrazy/Zaznaczenie_005.png thumbnail already exists
> GLib-CRITICAL **: Source ID 182 was not found when attempting to remove it at /usr/bin/shutter line 7262.
> screenshot successfully saved to /home/pyroxar/Obrazy/Zaznaczenie_005.png!
> 
> fct_update_tray_menu was called by Gnome2::Wnck::Screen=HASH(0x55c600bcd548)
> GdkPixbuf-LOG **: gdk_pixbuf_from_pixdata() called on: at /usr/bin/shutter line 2891.
> GdkPixbuf-LOG **: 	Encoding raw at /usr/bin/shutter line 2891.
> GdkPixbuf-LOG **: 	Dimensions: 16 x 16 at /usr/bin/shutter line 2891.
> GdkPixbuf-LOG **: 	Rowstride: 64, Length: 1048 at /usr/bin/shutter line 2891.
> GdkPixbuf-LOG **: 	Copy pixels == false at /usr/bin/shutter line 2891.
> GdkPixbuf-LOG **: gdk_pixbuf_from_pixdata() called on: at /usr/bin/shutter line 2891.
> GdkPixbuf-LOG **: 	Encoding raw at /usr/bin/shutter line 2891.
> GdkPixbuf-LOG **: 	Dimensions: 16 x 16 at /usr/bin/shutter line 2891.
> GdkPixbuf-LOG **: 	Rowstride: 64, Length: 1048 at /usr/bin/shutter line 2891.
> GdkPixbuf-LOG **: 	Copy pixels == false at /usr/bin/shutter line 2891.
> 
> fct_update_tray_menu was called by Gnome2::Wnck::Screen=HASH(0x55c600bcd548)
> created - [5] - Zaznaczenie_005.png
> changed - [5] - Zaznaczenie_005.png
> file:///home/pyroxar/Obrazy/Zaznaczenie_005.png - changed
> Updating fileinfos REJECTED for key: [5] - Zaznaczenie_005.png (not modified)
> 
> fct_update_tray_menu was called by Gnome2::Wnck::Screen=HASH(0x55c600bcd548)
> 
> fct_update_tray_menu was called by Gnome2::Wnck::Screen=HASH(0x55c600bcd548)
> 
> fct_update_tray_menu was called by Gnome2::Wnck::Screen=HASH(0x55c600bcd548)
> 
> fct_update_tray_menu was called by Gnome2::Wnck::Screen=HASH(0x55c600bcd548)
> 
> progname_toggled was emitted by widget Gtk2::CheckButton=HASH(0x55c5fe9cfb58)
> 
> progname_toggled was emitted by widget Gtk2::CheckButton=HASH(0x55c5fe9cfb58)
> GLib-CRITICAL **: Source ID 1207 was not found when attempting to remove it at /usr/bin/shutter line 7262.
> 
> fct_update_tray_menu was called by Gnome2::Wnck::Screen=HASH(0x55c600bcd548)
> GdkPixbuf-LOG **: gdk_pixbuf_from_pixdata() called on: at /usr/bin/shutter line 2891.
> GdkPixbuf-LOG **: 	Encoding raw at /usr/bin/shutter line 2891.
> GdkPixbuf-LOG **: 	Dimensions: 16 x 16 at /usr/bin/shutter line 2891.
> GdkPixbuf-LOG **: 	Rowstride: 64, Length: 1048 at /usr/bin/shutter line 2891.
> GdkPixbuf-LOG **: 	Copy pixels == false at /usr/bin/shutter line 2891.
> GdkPixbuf-LOG **: gdk_pixbuf_from_pixdata() called on: at /usr/bin/shutter line 2891.
> GdkPixbuf-LOG **: 	Encoding raw at /usr/bin/shutter line 2891.
> GdkPixbuf-LOG **: 	Dimensions: 16 x 16 at /usr/bin/shutter line 2891.
> GdkPixbuf-LOG **: 	Rowstride: 64, Length: 1048 at /usr/bin/shutter line 2891.
> GdkPixbuf-LOG **: 	Copy pixels == false at /usr/bin/shutter line 2891.
> 
> fct_update_tray_menu was called by Gnome2::Wnck::Screen=HASH(0x55c600bcd548)

and second test for the xed: success.

> 
> select was emitted by widget Gtk2::ToolButton=HASH(0x55c5fea3eb40)
> 3 Ns used in wild-card
> Searching for files with pattern: (?^u:\$name_(\d\d\d)\.png)
> Searching for files with pattern: (?^u:.{1,}_(\d\d\d)\.png)
> Comparing Zaznaczenie_005.png
> 005 is currently greatest value...
> Comparing d4.png
> Comparing Zaznaczenie_003.png
> Comparing d1.png
> Comparing d2.png
> Comparing Richard Stallman - We're heading for a total disaster-uFMMXRoSxnA.webm
> Comparing Zaznaczenie_004.png
> Comparing Zaznaczenie_002.png
> Comparing d3.png
> Comparing Zaznaczenie_001.png
> Comparing Zrzut ekranu z 2019-07-19 21-54-46.png
> Using monitor: 0 - 0 - 1920 - 1080
> Parsing wildcards for /home/pyroxar/Obrazy/$name_006.png
> Parsed $width and $height: /home/pyroxar/Obrazy/$name_006.png
> Parsed $profile: /home/pyroxar/Obrazy/$name_006.png
> Parsed $name: /home/pyroxar/Obrazy/Zaznaczenie_006.png
> New uri after exists check: file:///home/pyroxar/Obrazy/Zaznaczenie_006.png
> Trying to save file to /home/pyroxar/Obrazy/Zaznaczenie_006.png
> Saving file /home/pyroxar/Obrazy/Zaznaczenie_006.png, png, 9
> Updating fileinfos for key: [6] - Zaznaczenie_006.png
> file:///home/pyroxar/Obrazy/Zaznaczenie_006.png thumbnail created
> file:///home/pyroxar/Obrazy/Zaznaczenie_006.png thumbnail already exists
> GLib-CRITICAL **: Source ID 2084 was not found when attempting to remove it at /usr/bin/shutter line 7262.
> screenshot successfully saved to /home/pyroxar/Obrazy/Zaznaczenie_006.png!
> GLib-CRITICAL **: Source ID 1209 was not found when attempting to remove it at /usr/share/perl5/Shutter/App/ShutterNotification.pm line 186.
> 
> fct_update_tray_menu was called by Gnome2::Wnck::Screen=HASH(0x55c600bcd548)
> 
> fct_update_tray_menu was called by Gnome2::Wnck::Screen=HASH(0x55c600bcd548)
> created - [6] - Zaznaczenie_006.png
> changed - [6] - Zaznaczenie_006.png
> file:///home/pyroxar/Obrazy/Zaznaczenie_006.png - changed
> Updating fileinfos REJECTED for key: [6] - Zaznaczenie_006.png (not modified)
> 
> fct_update_tray_menu was called by Gnome2::Wnck::Screen=HASH(0x55c600bcd548)

**Comment by clefebvre** [comment]
That's upstream from us.
