### ISSUE TITLE
Caja doesn't keep extra panel/no extra panel state

### ISSUE THREAD

**Issue by InfoLibre** [linuxmint/mint19.2-beta#55]
**Describe the bug**
Caja doesn't keep extra panel/no extra panel state. We need always to press F3 after Caja starting.

**To Reproduce**
1. Start Caja
2. Press on F3 to have 2 panels
3. Quit Caja
4. Start Caja : only one panel !

**Expected behavior**
Caja should start with one panel when we quit it with one panel and it should start with two panels when we quit it with two panels.

**Frequency**
Does the issue happen:
- [x] Always
- [ ] Randomly

**Edition (Desktop environment):**
- [x] MATE Edition
- [ ] Xfce Edition

**Live or post-install:**
Indicate if this is happening after the installation, or during the live session:
- [x] Post-install
- [ ] Live session

**Additional context**
https://github.com/mate-desktop/caja/issues/277

**Comment by clefebvre** [comment]
This should be a feature request against Caja. I'm sorry the original was closed. I'd suggest to either getting it reopened or to create a new one.
