### ISSUE TITLE
In Caja, impossible to associate some softwares with Read a video DVD...

### ISSUE THREAD

**Issue by InfoLibre** [linuxmint/mint19.2-beta#56]
**Describe the bug**
In Caja, impossible to associate some softwares with "Read a video DVD"...

See https://github.com/mate-desktop/caja/issues/277

**Comment by clefebvre** [comment]
I don't understand the issue... you mean the default handler for DVD insertion?

Either way, this should be done directly in github.com/mate-desktop.

**Comment by InfoLibre** [comment]
Sorry, I made a mistake, the right links are :
https://github.com/linuxmint/linuxmint/issues/54
https://github.com/mate-desktop/caja/issues/581
https://github.com/mate-desktop/caja/issues/569
https://github.com/clementine-player/Clementine/issues/5417
