### ISSUE TITLE
Unable to edit application launcher pinned to taskbar

### ISSUE THREAD

**Issue by m5benson** [linuxmint/mint19.2-beta#57]
**Describe the bug**
I have been a huge fan of Linux Mint for many years.  Thank you for all your hard work!
After pinning an application launcher to the primary taskbar, I like to edit the pinned launcher to change the icon and also to point to a heavily-used web address, such as YouTube.  So, in effect, I am "hijacking" the application launcher to become something very different.  

**To Reproduce**
1. click on Linux Mint start button
2. find the Accessibility application under All Applications
3. hover the mouse over Accessibility such that Accessibility highlights, then right-click on that application
4. left-click on "+ Add To Panel"
5. right-click the newly-pinned Accessibility application on the taskbar
6. at this point, you are given three options: (1) Preferences, (2) New Window, or (3) Unpin from Panel
7. none of these options allows you to edit the pinned launcher

**Observed behavior screenshot:**
![Linux MInt 19 2 Behavior](https://user-images.githubusercontent.com/53152831/61596226-618cc300-abc6-11e9-8d11-93533ed0e32c.jpg)

**Expected behavior:** 
Older versions of Cinnamon (in Mint 17, 18, 19.1) allow you to do this.
In step (6) above, I expect to see an additional "Edit" choice, that allows me to change the icon and change the command.  See two (2) attached screenshots, which show the desired dialog boxes from Linux Mint 19.1.

![Linux Mint 19 1 Behavior](https://user-images.githubusercontent.com/53152831/61596039-ecb88980-abc3-11e9-8c60-93df85f38b59.jpg)

![Launcher Properties Dialog Box](https://user-images.githubusercontent.com/53152831/61596142-63a25200-abc5-11e9-812a-cd9bf74b46d6.png)

**Frequency**
Does the issue happen:
- [X] Always
- [ ] Randomly

**Edition (Desktop environment):**
In which edition is this happening?
- [X] Cinnamon Edition
- [ ] MATE Edition
- [ ] Xfce Edition

**Live or post-install:**
Indicate if this is happening after the installation, or during the live session:
- [X] Post-install
- [ ] Live session

**Screenshots**

**Locale:**
Paste the output of `locale`.
LANG=en_US.UTF-8
LANGUAGE=en_US
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=

**Drivers:**
Paste the output of `inxi -Gxx`.
Graphics:
  Device-1: Intel driver: i915 v: kernel bus ID: 00:02.0 chip ID: 8086:3ea5 
  Display: x11 server: X.Org 1.19.6 driver: modesetting unloaded: fbdev,vesa 
  resolution: 1920x1080~60Hz 
  OpenGL: renderer: Mesa DRI Intel HD Graphics (Coffeelake 3x8 GT3) 
  v: 4.5 Mesa 19.0.2 compat-v: 3.0 direct render: Yes 

**Crash report:**
There is no crash.

''Stack trace''
If you are reporting a crash. Go to "Software Sources" and enable the debug symbols. Then go to "System Reports" and extract the stack trace for your crash and paste it here.
There is no crash.

''Dmesg''
If you type `dmesg` in a terminal, you should see a line corresponding to the crash. Paste it here.
There is no crash.

**Additional context**
There is no other context.

**Comment by kacperpaczos** [comment]
I confirm this bug.

**Comment by clefebvre** [comment]
That's not a bug. The Grouped Window List applet isn't meant to do this. There's an applet for that exact purpose though, it's Panel Launchers.

**Comment by m5benson** [comment]
Yes, you are right - I had forgotten that I had this same problem with 19.1, and removed "Grouped window list" application from the panel.
https://superuser.com/questions/1405990/how-to-mint-19-cinnamon-taskbar-application-remove-grouping
