### ISSUE TITLE
mintmenu: menu is not automatically updated

### ISSUE THREAD

**Issue by segadora** [linuxmint/mint19.2-beta#58]
**Describe the bug**
When installing a new program, the program does not appear in the menu after installation.

**To Reproduce**
1. Install program like slack, enpass, google chrome
2. After install, the program does not appear in the menu
3. After logout, the program will appear in the menu

**Expected behavior**
I expect to see the newly installed program in the menu

**Frequency**
Does the issue happen:
- [x] Always
- [ ] Randomly

**Edition (Desktop environment):**
In which edition is this happening?
- [ ] Cinnamon Edition
- [x] MATE Edition
- [ ] Xfce Edition

**Live or post-install:**
Indicate if this is happening after the installation, or during the live session:
- [x] Post-install
- [ ] Live session

**Screenshots**
![image](https://user-images.githubusercontent.com/6637534/61620309-ee8c5680-ac70-11e9-8d5d-b08d406b9f33.png)

**Locale:**
```
LANG=da_DK.UTF-8
LANGUAGE=da
LC_CTYPE="da_DK.UTF-8"
LC_NUMERIC="da_DK.UTF-8"
LC_TIME="da_DK.UTF-8"
LC_COLLATE="da_DK.UTF-8"
LC_MONETARY="da_DK.UTF-8"
LC_MESSAGES="da_DK.UTF-8"
LC_PAPER="da_DK.UTF-8"
LC_NAME="da_DK.UTF-8"
LC_ADDRESS="da_DK.UTF-8"
LC_TELEPHONE="da_DK.UTF-8"
LC_MEASUREMENT="da_DK.UTF-8"
LC_IDENTIFICATION="da_DK.UTF-8"
LC_ALL=
```

**Drivers:**
```
Graphics:
  Device-1: Intel vendor: Lenovo driver: i915 v: kernel bus ID: 00:02.0 
  chip ID: 8086:3ea0 
  Display: x11 server: X.Org 1.19.6 driver: modesetting unloaded: fbdev,vesa 
  compositor: marco 
  resolution: 1920x1080~60Hz, 2560x1440~60Hz, 2560x1440~60Hz 
  OpenGL: renderer: Mesa DRI Intel HD Graphics (Whiskey Lake 3x8 GT2) 
  v: 4.5 Mesa 19.0.2 compat-v: 3.0 direct render: Yes
```

**Crash report:**

''Stack trace''
If you are reporting a crash. Go to "Software Sources" and enable the debug symbols. Then go to "System Reports" and extract the stack trace for your crash and paste it here.

''Dmesg''
If you type `dmesg` in a terminal, you should see a line corresponding to the crash. Paste it here.

**Additional context**

**Comment by clefebvre** [comment]
I can't reproduce this issue.

apt install filezilla -> it appears in the menu
apt remove filezilla -> it's gone again

**Comment by segadora** [comment]
Works now, so it may have been fixed in some update.
