### ISSUE TITLE
QT5 Settings can not be translated into other languages like Portuguese brazil?

### ISSUE THREAD

**Issue by VaGNaroK** [linuxmint/mint19.2-beta#59]
**Describe the bug**
it's not a bug

**To Reproduce**
...

**Frequency**
Does the issue happen:
- [x] Always
- [ ] Randomly

**Edition (Desktop environment):**
In which edition is this happening?
- [x] Cinnamon Edition
- [ ] MATE Edition
- [ ] Xfce Edition

**Screenshots**
https://postimg.cc/SXYrNSNS

**Additional context**
I am part of the brazilian portuguese translation team and qt settings has no sources to translate via launchpad, would i have how to translate the tool for brazilian users?

**Comment by NikoKrause** [comment]
Qt5 Configuration Tool is doing its translations on https://www.transifex.com/qt5-configuration-tool/qt5ct/

**Comment by VaGNaroK** [comment]
> Qt5 Configuration Tool is doing its translations on https://www.transifex.com/qt5-configuration-tool/qt5ct/

thank you very much.
