### ISSUE TITLE
Backspace key does not work in Xapps dialog box

### ISSUE THREAD

**Issue by antrrax** [linuxmint/mint19.2-beta#6]
**Describe the bug**
Backspace key does not work in Xapps dialog box
Dialogs: Open Files and Save As...

**To Reproduce**
XED
1. Menu File
2. Open...
3. XED - dialog box: Open Files
4. Type Backspace (no action)

**Expected behavior**
Backspace key should return a directory level, as it does in Nemo.
example:
path: "/home/beta/Downloads", type "Backspace key" , go to "/home/beta"

**Frequency**
Does the issue happen:
- [x ] Always
- [ ] Randomly

**Edition (Desktop environment):**
In which edition is this happening?
- [ x] Cinnamon Edition
- [ ] MATE Edition
- [ ] Xfce Edition

**Live or post-install:**
Indicate if this is happening after the installation, or during the live session:
- [ x] Post-install
- [ ] Live session

Note: Backspace key, Also does not work in App USB Image Writer > Dialog box: Select Image

**Comment by JosephMcc** [comment]
Again we have no control over this. This dialog is provided by Gtk. Bugs with it need to be reported upstream.

**Comment by clefebvre** [comment]
Absolutely. It's a very valid bug but it should be reported to GNOME GTK directly: https://gitlab.gnome.org/GNOME/gtk.
