### ISSUE TITLE
Duplicate "online accounts" icon.

### ISSUE THREAD

**Issue by VaGNaroK** [linuxmint/mint19.2-beta#60]
**Describe the bug**
When you look in the "Online Accounts" menu you will see 2 identical icons from the same service, each leading to the same place.

**To Reproduce**
1. Go to 'Menu'
2. Click on 'Search'
3. type it 'Online Accounts'

**Expected behavior**
Duplicate Icon and Names

**Frequency**
Does the issue happen:
- [x] Always
- [ ] Randomly

**Edition (Desktop environment):**
In which edition is this happening?
- [x] Cinnamon Edition
- [ ] MATE Edition
- [ ] Xfce Edition

**Screenshots**
https://postimg.cc/zy5QjN4G

**Locale:**
LANG=pt_BR.UTF-8
LANGUAGE=pt_BR:pt
LC_CTYPE="pt_BR.UTF-8"
LC_NUMERIC=pt_BR.UTF-8
LC_TIME=pt_BR.UTF-8
LC_COLLATE="pt_BR.UTF-8"
LC_MONETARY=pt_BR.UTF-8
LC_MESSAGES="pt_BR.UTF-8"
LC_PAPER=pt_BR.UTF-8
LC_NAME=pt_BR.UTF-8
LC_ADDRESS=pt_BR.UTF-8
LC_TELEPHONE=pt_BR.UTF-8
LC_MEASUREMENT=pt_BR.UTF-8
LC_IDENTIFICATION=pt_BR.UTF-8
LC_ALL=

**Drivers:**
Graphics:
  Device-1: NVIDIA G96 [GeForce 9500 GT] vendor: eVga.com. driver: nouveau 
  v: kernel bus ID: 01:00.0 chip ID: 10de:0640 
  Display: x11 server: X.Org 1.19.6 driver: nouveau 
  unloaded: fbdev,modesetting,vesa resolution: 1366x768~60Hz 
  OpenGL: renderer: NV96 v: 3.3 Mesa 19.0.2 direct render: Yes

**Comment by clefebvre** [comment]
Already fixed in Git, pending update. https://github.com/linuxmint/cinnamon-control-center/commit/8a63faf8d9b85188c78b11fe9af2f92c0907bbd5
