### ISSUE TITLE
mintupdate: missing Levels and Auto-refresh tabs in Preferences?

### ISSUE THREAD

**Issue by thegreatyellow67** [linuxmint/mint19.2-beta#69]
Hi, I'm testing Mint 19.2 Cinnamon on a VM. I realized that Levels and Auto-Refresh tabs no longer appear in mintupdate preferences. Is it a wanted change? Won't be no longer possible to choose levels of system update? Thank you.

**Comment by kelebek333** [comment]
[New features in Linux Mint 19.2 Cinnamon](https://www.linuxmint.com/rel_tina_cinnamon_whatsnew.php)
