### ISSUE TITLE
New warning on mintupdate (5.5.1) Command Line Update

### ISSUE THREAD

**Issue by Harry-W-Haines-III** [linuxmint/mint19.2-beta#70]
**Describe the bug**
Noticed today a warning that had never been seen before doing a command line update with the command: "sudo mintupdate-cli -y upgrade"

Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages will be upgraded:
  mintupdate
1 upgraded, 0 newly installed, 0 to remove and 121 not upgraded.
Need to get 0 B/550 kB of archives.
After this operation, 28.7 kB disk space will be freed.
(Reading database ... 438379 files and directories currently installed.)
Preparing to unpack .../mintupdate_5.5.1_all.deb ...
Unpacking mintupdate (5.5.1) over (5.4.9) ...

"dpkg: warning: unable to delete old directory '/usr/lib/linuxmint/mintUpdate/__pycache__': Directory not empty"

Setting up mintupdate (5.5.1) ...

**To Reproduce**
1. Go to 'Start Menu'
2. Click on 'Terminal'
3. type "sudo mintupdate-cli -y upgrade"

**Expected behavior**
Not expecting to see this warning as it did not appear in the past.

**Frequency**
Does the issue happen:
- [x] Always
- [ ] Randomly

**Edition (Desktop environment):**
In which edition is this happening?
- [x] Cinnamon Edition
- [ ] MATE Edition
- [ ] Xfce Edition

**Live or post-install:**
Indicate if this is happening after the installation, or during the live session:
- [x] Post-install
- [ ] Live session

**Screenshots**
N/A

**Locale:**
LANG=en_US.UTF-8
LANGUAGE=en_US
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=

**Drivers:**
N/A

**Crash report:**
None

''Stack trace''
If you are reporting a crash. Go to "Software Sources" and enable the debug symbols. Then go to "System Reports" and extract the stack trace for your crash and paste it here.

''Dmesg''
If you type `dmesg` in a terminal, you should see a line corresponding to the crash. Paste it here.

**Additional context**
Warning message is solid and repeatable.
'/usr/lib/linuxmint/mintUpdate/__pycache__': Directory not empty
is the actual message.  After making the message bold, the under scores went away and can't get them to show again.

See screenshot:

![Screenshot-from-2019-07-26-16-55-14](https://user-images.githubusercontent.com/45599505/61980971-448d3100-afc6-11e9-9efc-889bff4b2401.png)

**Comment by Harry-W-Haines-III** [comment]
dpkg: warning: unable to delete old directory '/usr/lib/linuxmint/mintUpdate/__pycache__': Directory not empty

Is the actual message.

**Comment by clefebvre** [comment]
This folder could be the result of a mintupdate instance run as root. You can safely delete it.
