### ISSUE TITLE
I have found 1 Problem

### ISSUE THREAD

**Issue by Palladini** [linuxmint/mint19.2-beta#75]
I have an ASUS P8P67 Pro MB, Intel I7 Skylake CPU, 32 GB Ram, and a 2 GB Nvidia Graphics card.  I run 2 Monitors
I was on my computer and running Linux Mint 19.2 cinnamon, and I opened a Libre office writer Document, minimized it and when I clicked on it in the Menu bar, it opened, but if I moved my mouse, it would disappear.  I clicked on the item in the menu bar many times and every time I clicked on it moved my mouse, the Document disappeared.  
That has only happened once, otherwise, Linux Mint 19.2 has been a rock-solid OS

**Comment by clefebvre** [comment]
This is only an observation at this stage of troubleshooting (https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/).
