### ISSUE TITLE
mate-control-center's window tiling error

### ISSUE THREAD

**Issue by bagjunggyu** [linuxmint/mint19.2-beta#9]
**Describe the bug**
Drag the window to the corner
It doesn't work for expected behaviour

**To Reproduce**
Drag the window to the corner
It doesn't work for expected behavior

**Expected behavior**
That window should be shrinked to fit for 4 corners

**Frequency**
Does the issue happen:
- [0] Always
- [ ] Randomly

**Edition (Desktop environment):**
In which edition is this happening?
- [ ] Cinnamon Edition
- [0] MATE Edition
- [ ] Xfce Edition

**Live or post-install:**
Indicate if this is happening after the installation, or during the live session:
- [0] Post-install
- [0] Live session

**Comment by JosephMcc** [comment]
You don't describe the what happens very well here. It would be nice if you said what it actually IS doing. Taking a random guess, if a window cannot be resized to fit the zone you are trying to tile it in, it will not tile.

**Comment by clefebvre** [comment]
![image](https://user-images.githubusercontent.com/1138515/61366607-2d459980-a88a-11e9-9933-d79fc8dbe5d1.png)

It's working quite well here.

If there isn't enough space in the resolution (i.e. if the window can't shrink to half the res size both horizontally and vertically) most window managers will refuse to tile it. That's expected behavior.

**Comment by ghost** [comment]
@clefebvre , @JosephMcc 

Here is zipped mp4 video

[vokoscreen-2019-07-17_19-19-53.mp4.zip](https://github.com/linuxmint/mint19.2-beta/files/3401375/vokoscreen-2019-07-17_19-19-53.mp4.zip)

**Comment by clefebvre** [comment]
Yes, I think that's just it.. it doesn't fit in 430px or so (half your 900px minus the panel bar).

**Comment by cruftytheclown** [comment]
Instead of doing nothing, I think it should resize the window to as small as the window can be, and stick it in the corner.

**Comment by JosephMcc** [comment]
The current behavior is how other WM's handle that I know of. That is something you would probably want to bring up with the Mate devs.

**Comment by clefebvre** [comment]
@cruftytheclown that's what I mean, it probably can't be sized down to that size.

**Comment by ghost** [comment]
Yes, that's right it can't be sized down to that size(requested to fit for corner).
It ends with some portions. That is the limit. 
It is bigger than requested size.
